name: Deploy

permissions: 
  pull-requests: write 


on:
  pull_request:
    branches: [ main ]

jobs:
  testing-changes:
    runs-on: ubuntu-latest
    name: Build/Test
    steps:
    - uses: actions/checkout@v2

    - name: NPM - Install dependencies
      if: steps.cached-npm-dependencies.outputs.cache-hit != 'true'
      run: 'npm install'

    - name: Run Tests
      run: |
        npm run test

  deploy-env:
    name: Deploy Lambda
    runs-on: ubuntu-latest
    needs: testing-changes
    steps:
    - uses: actions/checkout@v2

    - name: NPM - Load cached venv
      id: cached-npm-dependencies
      uses: actions/cache@v2
      with:
        path: node_modules
        key: npm-${{ runner.os }}-${{ hashFiles('**/package.json') }}

    - name: NPM - Install dependencies
      if: steps.cached-npm-dependencies.outputs.cache-hit != 'true'
      run: 'npm install'

    - name: Deploy using sls
      run: 'echo "Deploying..." && sleep 5'

    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v1
      with:
        message: |
          Your changes were deployed!

        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}